# Generated by Django 5.0.6 on 2024-05-08 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrainAPI', '0002_station'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='train',
            name='wagon0',
        ),
        migrations.RemoveField(
            model_name='train',
            name='wagon1',
        ),
        migrations.RemoveField(
            model_name='train',
            name='wagon2',
        ),
        migrations.RemoveField(
            model_name='train',
            name='wagon3',
        ),
        migrations.RemoveField(
            model_name='train',
            name='wagon4',
        ),
        migrations.RemoveField(
            model_name='train',
            name='wagon5',
        ),
        migrations.RemoveField(
            model_name='train',
            name='wagon6',
        ),
        migrations.RemoveField(
            model_name='train',
            name='wagon7',
        ),
        migrations.CreateModel(
            name='Wagon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('wagon_type', models.CharField(max_length=100)),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TrainAPI.train')),
            ],
        ),
    ]
