# Generated by Django 5.0.6 on 2024-05-08 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrainAPI', '0003_remove_train_wagon0_remove_train_wagon1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='next_station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='next_stations', to='TrainAPI.station'),
        ),
        migrations.AlterField(
            model_name='train',
            name='prev_station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prev_stations', to='TrainAPI.station'),
        ),
    ]
