# Generated by Django 5.0.6 on 2024-05-12 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrainAPI', '0004_alter_train_next_station_alter_train_prev_station'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=12, max_digits=16)),
                ('lon', models.DecimalField(decimal_places=12, max_digits=16)),
            ],
        ),
        migrations.AddField(
            model_name='station',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TrainAPI.location'),
        ),
    ]
